baseURL = '/'
languageCode = 'en-us'
title = 'Aureum Medium LLC'
theme = "PaperMod"

[markup.goldmark.renderer]
  unsafe = true

[params]
  defaultTheme = 'light'
  disableThemeToggle = true

[params.homeInfoParams]
Title = "aureum medium (Latin)"
Content = "<b>golden mean</b><br/><br/>The software engineering consultancy of Reed G. Law"

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/aureummedium'

[[params.socialIcons]]
name = 'stackoverflow'
url = 'https://stackoverflow.com/users/439332/reed-g-law'

[[params.socialIcons]]
name = 'ycombinator'
url = 'https://news.ycombinator.com/user?id=reedlaw'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/reedglaw/'
